name: release

on:
  push:
    tags:
      - "v*"

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/pyplotutil/
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.3.2

      - name: Build distributions
        run: uv build

      - name: Publish to PyPI
        run: uv publish

# Local Variables:
# jinx-local-words: "pypi ubuntu uv"
# End:
